export const projectsData = [
  // --- Cycle 1 ---
  {
    id: 1,
    title: "Custom Kitchen Cabinets",
    category: "Carpentry",
    description: "Complete overhaul and installation of modern wooden cabinetry and shelving.",
    location: "F-7, Islamabad",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 31,
    title: "Premium Wood Polishing",
    category: "Wood Polishing",
    description: "Restoring natural grain luster and deep finish to vintage hardwood furniture sets.",
    location: "DHA Phase 2, Islamabad",
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 11,
    title: "Aesthetic PVC Wall Panelling",
    category: "PVC Panelling",
    description: "Durable moisture-resistant PVC wall panels installed for a contemporary feature wall.",
    location: "F-10, Islamabad",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 21,
    title: "Luxury Glass Partition",
    category: "Aluminium & Glass",
    description: "Sleek minimalist aluminium framing with tempered glass partitions for office division.",
    location: "Bahria Town, Islamabad",
    image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 41,
    title: "Structural Security Gate",
    category: "Welding",
    description: "Custom heavy-duty iron main gate fabrication and automated rail installation.",
    location: "G-11, Islamabad",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 2 ---
  {
    id: 2,
    title: "Bespoke Master Walk-in Closet",
    category: "Carpentry",
    description: "Floor-to-ceiling built-in wooden wardrobes with integrated drawer compartments.",
    location: "E-7, Islamabad",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 32,
    title: "Hardwood Staircase Refinishing",
    category: "Wood Polishing",
    description: "Sanding, staining, and protective gloss coating for solid oak wooden steps and handrails.",
    location: "F-8, Islamabad",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 12,
    title: "Commercial False Ceiling",
    category: "PVC Panelling",
    description: "False ceiling installation using high-grade insulated PVC panels with integrated LED lighting.",
    location: "Blue Area, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 22,
    title: "Aluminium Sliding Windows",
    category: "Aluminium & Glass",
    description: "Double-glazed soundproof aluminium window frames fitted across a double-story villa.",
    location: "PWD Colony, Islamabad",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 42,
    title: "Architectural Balcony Railing",
    category: "Welding",
    description: "Custom steel and wrought iron safety railings designed for modern exterior facades.",
    location: "Gulberg Greens, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 3 ---
  {
    id: 3,
    title: "Solid Wood Pergola",
    category: "Carpentry",
    description: "Treated timber outdoor garden pergola built for shaded patio lounging.",
    location: "DHA Phase 2, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 33,
    title: "Antique Dining Table Restoration",
    category: "Wood Polishing",
    description: "Deep chemical stripping and French polish application on a legacy dining set.",
    location: "F-6, Islamabad",
    image: "https://images.unsplash.com/photo-1617806118233-18e1c0c5512b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 13,
    title: "Bathroom Waterproof PVC Cladding",
    category: "PVC Panelling",
    description: "Seamless waterproof PVC panels installed to prevent moisture seeping in washrooms.",
    location: "G-13, Islamabad",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 23,
    title: "Minimalist Glass Shower Enclosure",
    category: "Aluminium & Glass",
    description: "Frameless tempered glass shower door installation with corrosion-resistant brass hinges.",
    location: "DHA Phase 1, Islamabad",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 43,
    title: "Heavy-Duty Steel Roof Truss",
    category: "Welding",
    description: "Fabrication and arc-welding of structural steel overhead shed roof trusses.",
    location: "I-10 Industrial Area, Islamabad",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 4 ---
  {
    id: 4,
    title: "Decorative Wooden Wall Panelling",
    category: "Carpentry",
    description: "Custom fluted wooden wall accents designed for a luxurious living room space.",
    location: "F-10, Islamabad",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 34,
    title: "Matt Finish Wooden Doors Refinishing",
    category: "Wood Polishing",
    description: "Duco matte lacquer coating applied uniformly across all interior wooden room doors.",
    location: "Gulberg Greens, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 14,
    title: "Basement Moisture-Proof Wall Lining",
    category: "PVC Panelling",
    description: "Protective PVC panel cladding to insulate and protect underground damp walls.",
    location: "F-6, Islamabad",
    image: "https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 24,
    title: "Frameless Glass Entrance Facade",
    category: "Aluminium & Glass",
    description: "Heavy-duty commercial glass entrance facade with automated aluminium sliding doors.",
    location: "Blue Area, Islamabad",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 44,
    title: "Decorative Window Security Grills",
    category: "Welding",
    description: "Modern minimalist steel bar burglar-proof window grills with anti-rust coating.",
    location: "PWD Colony, Islamabad",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 5 ---
  {
    id: 5,
    title: "Custom TV Entertainment Media Wall",
    category: "Carpentry",
    description: "Floating wooden console and heavy-duty back panel integration with concealed wiring.",
    location: "Bahria Town, Islamabad",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 35,
    title: "Hardwood Flooring Sanding & Polishing",
    category: "Wood Polishing",
    description: "Re-buffing and polyurethane coat sealing for solid teak parquet flooring.",
    location: "E-7, Islamabad",
    image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 15,
    title: "Modern 3D PVC Wall Accents",
    category: "PVC Panelling",
    description: "Textured 3D architectural PVC panels fitted behind master bedroom headboards.",
    location: "Bahria Town, Islamabad",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 25,
    title: "Aluminium Louvre Vent Windows",
    category: "Aluminium & Glass",
    description: "Weather-proof louvered aluminium ventilation windows for mechanical rooms.",
    location: "G-9, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 45,
    title: "Spiral Metal Staircase Fabrication",
    category: "Welding",
    description: "Space-saving heavy steel spiral staircase built for rooftop service access.",
    location: "Bahria Town, Islamabad",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 6 ---
  {
    id: 6,
    title: "Hardwood Staircase Handrails",
    category: "Carpentry",
    description: "Custom-carved solid oak wooden handrails and balusters for duplex villas.",
    location: "G-11, Islamabad",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 36,
    title: "Built-In Wardrobe Re-Polishing",
    category: "Wood Polishing",
    description: "Surface scratch repair, re-staining, and clear satin gloss finish application.",
    location: "Bahria Town, Islamabad",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 16,
    title: "Kitchen Backsplash PVC Sheets",
    category: "PVC Panelling",
    description: "Heat-resistant, easy-to-clean decorative PVC sheets installed over kitchen counters.",
    location: "DHA Phase 1, Islamabad",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 26,
    title: "Tempered Glass Balustrade",
    category: "Aluminium & Glass",
    description: "Clear safety glass railing panels secured with slim aluminium base channels for balconies.",
    location: "F-8, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 46,
    title: "Boundary Wall Steel Spike Fencing",
    category: "Welding",
    description: "Perimeter security spiked steel fence installation over residential boundary walls.",
    location: "DHA Phase 2, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 7 ---
  {
    id: 7,
    title: "Office Executive Conference Table",
    category: "Carpentry",
    description: "Bespoke 12-seater conference table crafted from premium locally sourced walnut.",
    location: "Blue Area, Islamabad",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 37,
    title: "Outdoor Wooden Deck Coating",
    category: "Wood Polishing",
    description: "Weather-resistant anti-fungal oil treatment and stain sealant for pool decks.",
    location: "DHA Phase 4, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 17,
    title: "Balcony Weatherproof PVC Ceiling",
    category: "PVC Panelling",
    description: "UV-resistant exterior PVC ceiling panels built to withstand harsh climate changes.",
    location: "E-11, Islamabad",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 27,
    title: "Folding Aluminium Patio Doors",
    category: "Aluminium & Glass",
    description: "Multi-fold glass patio doors framed in powder-coated dark grey aluminium profiles.",
    location: "DHA Phase 5, Islamabad",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 47,
    title: "Industrial Storage Metal Racks",
    category: "Welding",
    description: "Custom bolted and welded high-capacity steel shelving racks for basement storage.",
    location: "G-13, Islamabad",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 8 ---
  {
    id: 8,
    title: "Custom Study Room Bookshelves",
    category: "Carpentry",
    description: "Full-wall built-in wooden bookshelves with integrated soft-closing cabinetry.",
    location: "F-8, Islamabad",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 38,
    title: "Wooden Console & Sideboard Refinishing",
    category: "Wood Polishing",
    description: "Dark walnut stain enhancement and high-gloss mirror finish restoration.",
    location: "F-11, Islamabad",
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 18,
    title: "Office Corridor Acoustic PVC Panels",
    category: "PVC Panelling",
    description: "Sound-dampening hollow PVC wall panel installations for corporate hallways.",
    location: "I-8, Islamabad",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 28,
    title: "Skylight Structural Glass Framing",
    category: "Aluminium & Glass",
    description: "Custom structural aluminium grid framework fitted with laminated safety roof glass.",
    location: "E-7, Islamabad",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 48,
    title: "Metal Air Conditioning Outdoor Cages",
    category: "Welding",
    description: "Protective security cages welded for external split AC compressor units.",
    location: "F-10, Islamabad",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 9 ---
  {
    id: 9,
    title: "Solid Timber Exterior Main Door",
    category: "Carpentry",
    description: "Heavy-duty carved solid teak wood main entrance door with weather sealant.",
    location: "Gulberg Greens, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 39,
    title: "Ceiling Wooden Beam Polishing",
    category: "Wood Polishing",
    description: "Scraping, sanding, and rich timber polish treatment for exposed ceiling beams.",
    location: "Chaklala Scheme 3, Rawalpindi / Islamabad Border",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 19,
    title: "Wardrobe Interior PVC Lining",
    category: "PVC Panelling",
    description: "Clean finish PVC panel sheet lining inside walk-in closets to stop humidity damage.",
    location: "F-7, Islamabad",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 29,
    title: "Frosted Glass Office Cabin Doors",
    category: "Aluminium & Glass",
    description: "Acid-etched frosted glass doors with heavy aluminium patch fittings.",
    location: "I-9, Islamabad",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 49,
    title: "Custom Gate Motor Sliding Track",
    category: "Welding",
    description: "Precision-aligned steel guide tracks welded and anchored for automated gates.",
    location: "F-7, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },

  // --- Cycle 10 ---
  {
    id: 10,
    title: "Under-Stair Storage Drawers",
    category: "Carpentry",
    description: "Custom pull-out modular drawer system built into unused under-stair spaces.",
    location: "PWD Colony, Islamabad",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 40,
    title: "Main Entrance Door Melamine Polish",
    category: "Wood Polishing",
    description: "Durable scratch-proof melamine spray polish for exterior weatherproof protection.",
    location: "G-11, Islamabad",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 20,
    title: "Retail Store Display Backdrops",
    category: "PVC Panelling",
    description: "High-gloss finished marble-look PVC sheets fitted for retail boutique interiors.",
    location: "Saddar, Rawalpindi / Islamabad Border",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 30,
    title: "Aluminium Kitchen Cabinets Glass Shutters",
    category: "Aluminium & Glass",
    description: "Back-painted colored glass panels mounted inside durable aluminium frames.",
    location: "F-10, Islamabad",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 50,
    title: "Garden Metal Pergola Frame",
    category: "Welding",
    description: "Weather-coated structural steel tubular frame welded for garden climbing plants.",
    location: "E-11, Islamabad",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
  },
];